version = 0.1

[default.deploy.parameters]
stack_name = "maki-daily-report"
resolve_s3 = true
s3_prefix = "maki-daily-report"
profile = "jsl"
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "ap-northeast-1"
